// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrototypePrjEntityFramework.Data;

namespace PrototypePrjEntityFramework.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211026164303_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("PrototypePrjEntityFramework.Models.Allergene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AllergeneNome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Allergeni");
                });

            modelBuilder.Entity("PrototypePrjEntityFramework.Models.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nomeIngrediente")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ingredienti");
                });

            modelBuilder.Entity("PrototypePrjEntityFramework.Models.Menu", b =>
                {
                    b.Property<int>("RistoranteId")
                        .HasColumnType("int");

                    b.Property<int>("PiattoId")
                        .HasColumnType("int");

                    b.Property<float>("Prezzo")
                        .HasColumnType("float");

                    b.HasKey("RistoranteId", "PiattoId");

                    b.HasIndex("PiattoId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("PrototypePrjEntityFramework.Models.Piatto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomePiatto")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Piatti");
                });

            modelBuilder.Entity("PrototypePrjEntityFramework.Models.Preavvisi", b =>
                {
                    b.Property<int>("PiattoId")
                        .HasColumnType("int");

                    b.Property<int>("AllergeneId")
                        .HasColumnType("int");

                    b.HasKey("PiattoId", "AllergeneId");

                    b.HasIndex("AllergeneId");

                    b.ToTable("Preavvisi");
                });

            modelBuilder.Entity("PrototypePrjEntityFramework.Models.Procedimenti", b =>
                {
                    b.Property<int>("PiattoId")
                        .HasColumnType("int");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.HasKey("PiattoId", "IngredienteId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("Procedimenti");
                });

            modelBuilder.Entity("PrototypePrjEntityFramework.Models.Ristorante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Citta")
                        .HasColumnType("longtext");

                    b.Property<int>("NCivico")
                        .HasColumnType("int");

                    b.Property<string>("NomeRistorante")
                        .HasColumnType("longtext");

                    b.Property<string>("PIVA")
                        .HasColumnType("longtext");

                    b.Property<string>("RagioneSociale")
                        .HasColumnType("longtext");

                    b.Property<string>("Regione")
                        .HasColumnType("longtext");

                    b.Property<string>("Via")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ristoranti");
                });

            modelBuilder.Entity("PrototypePrjEntityFramework.Models.Menu", b =>
                {
                    b.HasOne("PrototypePrjEntityFramework.Models.Piatto", "Piatto")
                        .WithMany("Menus")
                        .HasForeignKey("PiattoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrototypePrjEntityFramework.Models.Ristorante", "Ristorante")
                        .WithMany("Menus")
                        .HasForeignKey("RistoranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piatto");

                    b.Navigation("Ristorante");
                });

            modelBuilder.Entity("PrototypePrjEntityFramework.Models.Preavvisi", b =>
                {
                    b.HasOne("PrototypePrjEntityFramework.Models.Allergene", "Allergene")
                        .WithMany("Allergeni")
                        .HasForeignKey("AllergeneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrototypePrjEntityFramework.Models.Piatto", "Piatto")
                        .WithMany("Allergeni")
                        .HasForeignKey("PiattoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergene");

                    b.Navigation("Piatto");
                });

            modelBuilder.Entity("PrototypePrjEntityFramework.Models.Procedimenti", b =>
                {
                    b.HasOne("PrototypePrjEntityFramework.Models.Ingrediente", "Ingrediente")
                        .WithMany("Ingredienti")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrototypePrjEntityFramework.Models.Piatto", "Piatto")
                        .WithMany("Ingredienti")
                        .HasForeignKey("PiattoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Piatto");
                });

            modelBuilder.Entity("PrototypePrjEntityFramework.Models.Allergene", b =>
                {
                    b.Navigation("Allergeni");
                });

            modelBuilder.Entity("PrototypePrjEntityFramework.Models.Ingrediente", b =>
                {
                    b.Navigation("Ingredienti");
                });

            modelBuilder.Entity("PrototypePrjEntityFramework.Models.Piatto", b =>
                {
                    b.Navigation("Allergeni");

                    b.Navigation("Ingredienti");

                    b.Navigation("Menus");
                });

            modelBuilder.Entity("PrototypePrjEntityFramework.Models.Ristorante", b =>
                {
                    b.Navigation("Menus");
                });
#pragma warning restore 612, 618
        }
    }
}
